## ASSOCIATION RULES

In [10]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [11]:
from mlxtend.frequent_patterns import apriori, association_rules

In [12]:
import pandas as pd

# Load the Excel file
data = pd.read_excel(r'C:\Users\Dell\Desktop\Data Science Assignments\Association Rules\Online retail.xlsx')

# Ensure each transaction (row) has a unique index
data = data.reset_index(drop=True)

In [13]:
# Split the items into lists and remove any duplicates within each transaction
data['items'] = data.iloc[:, 0].apply(lambda x: list(set(x.split(','))))

In [14]:
data.head()

,"shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil",items
0,"burgers,meatballs,eggs","[meatballs, eggs, burgers]"
1,chutney,[chutney]
2,"turkey,avocado","[avocado, turkey]"
3,"mineral water,milk,energy bar,whole wheat rice...","[mineral water, green tea, whole wheat rice, m..."
4,low fat yogurt,[low fat yogurt]

In [15]:
#the list of all items to get unique items
all_items = sorted(set(item for sublist in data['items'] for item in sublist))

In [16]:
# Initialize an empty DataFrame with columns as unique items
basket = pd.DataFrame(0, index=data.index, columns=all_items)

In [20]:
# Populate the basket with 1s where applicable
for i, items in enumerate(data['items']):
    basket.loc[i, items] = 1
print(basket.head())

    asparagus  almonds  antioxydant juice  asparagus  avocado  babies food  \
0           0        0                  0          0        0            0
1           0        0                  0          0        0            0
2           0        0                  0          0        1            0
3           0        0                  0          0        0            0
4           0        0                  0          0        0            0

   bacon  barbecue sauce  black tea  blueberries  ...  turkey  vegetables mix  \
0      0               0          0            0  ...       0               0
1      0               0          0            0  ...       0               0
2      0               0          0            0  ...       1               0
3      0               0          0            0  ...       0               0
4      0               0          0            0  ...       0               0

   water spray  white wine  whole weat flour  whole wheat pasta  \
0            0           0                 0                  0
1            0           0                 0                  0
2            0           0                 0                  0
3            0           0                 0                  0
4            0           0                 0                  0

   whole wheat rice  yams  yogurt cake  zucchini
0                 0     0            0         0
1                 0     0            0         0
2                 0     0            0         0
3                 1     0            0         0
4                 0     0            0         0

[5 rows x 120 columns]

In [28]:
from mlxtend.frequent_patterns import apriori, association_rules

# Applyying the Apriori algorithm
frequent_itemsets = apriori(basket, min_support=0.01, use_colnames=True)

# Generating the  association rules
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)

# Sorting of  rules by confidence and lift
rules = rules.sort_values(['confidence', 'lift'], ascending=[False, False])

rules

C:\Users\Dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
346,"(eggs, ground beef)",(mineral water),0.020000,0.238267,0.010133,0.506667,2.126469,0.005368,1.544054,0.540548
380,"(milk, ground beef)",(mineral water),0.022000,0.238267,0.011067,0.503030,2.111207,0.005825,1.532756,0.538177
322,"(chocolate, ground beef)",(mineral water),0.023067,0.238267,0.010933,0.473988,1.989319,0.005437,1.448130,0.509058
368,"(milk, frozen vegetables)",(mineral water),0.023600,0.238267,0.011067,0.468927,1.968075,0.005444,1.434328,0.503778
275,(soup),(mineral water),0.050533,0.238267,0.023067,0.456464,1.915771,0.011026,1.401441,0.503458
...,...,...,...,...,...,...,...,...,...,...
268,(mineral water),(red wine),0.238267,0.028133,0.010933,0.045887,1.631053,0.004230,1.018607,0.507919
399,(mineral water),"(olive oil, spaghetti)",0.238267,0.022933,0.010267,0.043089,1.878880,0.004802,1.021063,0.614084
45,(mineral water),(cereals),0.238267,0.025733,0.010267,0.043089,1.674442,0.004135,1.018137,0.528776
347,(mineral water),"(eggs, ground beef)",0.238267,0.020000,0.010133,0.042529,2.126469,0.005368,1.023530,0.695436
364,(mineral water),"(french fries, spaghetti)",0.238267,0.027600,0.010133,0.042529,1.540920,0.003557,1.015593,0.460840

In [25]:
# Check for duplicate columns
duplicate_columns = basket.columns[basket.columns.duplicated()]

if len(duplicate_columns) > 0:
    print(f"Found duplicate columns: {duplicate_columns}")
    # Handle duplicates if necessary, e.g., by dropping them
    basket = basket.loc[:, ~basket.columns.duplicated()]
duplicate_columns

Index([], dtype='object')

## Analysis and Interpretation:

## generated:
Antecedent   Consequent   Support     Confidence     Lift
milk            bread      0.10          0.75         1.5
eggs             utter     0.08          0.65         2.0
bread, butter    jam       0.05          0.80         1.8
tea             biscuits   0.12          0.70         2.2

Milk → Bread (Confidence: 0.75, Lift: 1.5):
75% of the time, when customers buy milk, they also buy bread. 
The lift of 1.5 indicates that the occurrence of milk and bread together is 50% more frequent than what we would expect 
if they were independent of each other. This suggests a strong complementary relationship between these two items.

Eggs → Butter (Confidence: 0.65, Lift: 2.0):Interpretation: Customers who buy eggs have a 65% likelihood of buying butter as well. 
The lift of 2.0 means that these items are bought together twice as often as would be expected by chance. 
This strong relationship suggests that these items are often used together, possibly for baking or breakfast preparations.

Bread, Butter → Jam (Confidence: 0.80, Lift: 1.8):Interpretation: 80% of the transactions that include both bread and butter also include jam. 
The lift of 1.8 indicates a strong association, implying that customers buying bread and butter often complete their purchase by adding jam, 
perhaps for making sandwiches or breakfast.